package main

import (
	"context"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"syscall"
	"time"

	"github.com/spf13/cobra"

	"github.com/fl0w1nd/proxy-rule-manager/internal/serve"
)

var serveCmd = &cobra.Command{
	Use:   "serve",
	Short: "Start HTTP server for file serving and update API",
	RunE: func(cmd *cobra.Command, args []string) error {
		runtimeOpts, err := resolveServeRuntime(cmd)
		if err != nil {
			return err
		}
		// A fresh container starts with an empty /data volume and no
		// config.yaml. Seed one so serve can boot without a pre-mounted
		// config; edit it later through the mounted volume.
		if err := ensureDefaultConfig(cfgFile); err != nil {
			return err
		}

		app, err := buildApp(runtimeOpts.DataDir)
		if err != nil {
			return err
		}

		// Guarantee a servable site before accepting traffic: reconciles
		// builtin assets and re-renders pages from persisted state when they
		// are missing or were generated by an older binary.
		if err := app.Engine.EnsureSite(); err != nil {
			app.Logger.Warn("site initialization failed", "error", err)
		}

		srv := serve.NewServer(app.Config, app.State, app.Engine, app.Updates, serve.Options{
			DataDir: runtimeOpts.DataDir, APIToken: runtimeOpts.AdminToken,
			ConfigFile: cfgFile, TrustedProxies: runtimeOpts.TrustedProxies,
		})
		handler := srv.Handler()

		addr := net.JoinHostPort(runtimeOpts.Host, strconv.Itoa(runtimeOpts.Port))
		httpSrv := &http.Server{
			Addr:         addr,
			Handler:      handler,
			ReadTimeout:  30 * time.Second,
			WriteTimeout: 120 * time.Second,
			IdleTimeout:  120 * time.Second,
		}

		serverErr := make(chan error, 1)
		go func() {
			app.Logger.Info("server starting", "addr", addr)
			serverErr <- httpSrv.ListenAndServe()
		}()

		// Start scheduler if configured
		app.Updates.StartScheduler()

		ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
		defer cancel()
		select {
		case <-ctx.Done():
		case err := <-serverErr:
			app.Updates.StopScheduler()
			if err != nil && err != http.ErrServerClosed {
				return fmt.Errorf("serve: %w", err)
			}
			return nil
		}

		app.Logger.Info("shutting down")
		app.Updates.StopScheduler()

		updateCtx, updateCancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer updateCancel()
		if err := app.Updates.Stop(updateCtx); err != nil {
			app.Logger.Error("update shutdown failed", "error", err)
		}

		shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer shutdownCancel()
		return httpSrv.Shutdown(shutdownCtx)
	},
}

func init() {
	rootCmd.AddCommand(serveCmd)
}

// ensureDefaultConfig writes a container-friendly default config to path when
// no config file exists yet, so a fresh container with an empty /data volume
// can boot without a pre-provided config.yaml.
func ensureDefaultConfig(path string) error {
	if _, err := os.Stat(path); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("stat config: %w", err)
	}
	if err := os.WriteFile(path, []byte(exampleConfig), 0o644); err != nil {
		return fmt.Errorf("write default config %s: %w", path, err)
	}
	fmt.Printf("No config at %s; wrote a default config. Edit it via the mounted volume and reload it from the admin board.\n", path)
	return nil
}
