package main

import (
	"context"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/spf13/cobra"

	"github.com/fl0w1nd/proxy-rule-manager/internal/serve"
)

var serveCmd = &cobra.Command{
	Use:   "serve",
	Short: "Start HTTP server for file serving and update API",
	RunE: func(cmd *cobra.Command, args []string) error {
		apiToken := strings.TrimSpace(os.Getenv("ADMIN_TOKEN"))
		if apiToken == "" {
			return fmt.Errorf("ADMIN_TOKEN environment variable is required")
		}

		app, err := buildApp()
		if err != nil {
			return err
		}

		// Guarantee a servable site before accepting traffic: reconciles
		// builtin assets and re-renders pages from persisted state when they
		// are missing or were generated by an older binary.
		if err := app.Engine.EnsureSite(); err != nil {
			app.Logger.Warn("site initialization failed", "error", err)
		}

		srv := serve.NewServer(app.Config, app.State, app.Engine, app.Updates, apiToken)
		handler := srv.Handler()

		addr := net.JoinHostPort(app.Config.Serve.Host, strconv.Itoa(app.Config.Serve.Port))
		httpSrv := &http.Server{
			Addr:         addr,
			Handler:      handler,
			ReadTimeout:  30 * time.Second,
			WriteTimeout: 120 * time.Second,
			IdleTimeout:  120 * time.Second,
		}

		serverErr := make(chan error, 1)
		go func() {
			app.Logger.Info("server starting", "addr", addr)
			serverErr <- httpSrv.ListenAndServe()
		}()

		// Start scheduler if configured
		stopScheduler := app.StartScheduler()

		ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
		defer cancel()
		select {
		case <-ctx.Done():
		case err := <-serverErr:
			stopScheduler()
			if err != nil && err != http.ErrServerClosed {
				return fmt.Errorf("serve: %w", err)
			}
			return nil
		}

		app.Logger.Info("shutting down")
		stopScheduler()

		updateCtx, updateCancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer updateCancel()
		if err := app.Updates.Stop(updateCtx); err != nil {
			app.Logger.Error("update shutdown failed", "error", err)
		}

		shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer shutdownCancel()
		return httpSrv.Shutdown(shutdownCtx)
	},
}

func init() {
	rootCmd.AddCommand(serveCmd)
}
