[changelog]
header = """
"""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
## {{ group }}
{% for commit in commits %}
- {{ commit.message | trim }} ({{ commit.id | truncate(length=7, end="") }})
{% endfor %}

{% endfor %}
"""
footer = """
"""
trim = true

[git]
conventional_commits = false
filter_unconventional = false
split_commits = false
topo_order = false
sort_commits = "oldest"
commit_preprocessors = [
  { pattern = '(?s)\n.*$', replace = '' },
]
commit_parsers = [
  { message = '.*bump version to .*', skip = true },
  { message = '^Merge .*', skip = true },
  { message = '^[^[:alnum:]]*feat(?:\([^)]+\))?: .*$', group = 'feature' },
  { message = '^[^[:alnum:]]*fix(?:\([^)]+\))?: .*$', group = 'fix' },
  { message = '.*', group = 'misc' },
]
