// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/geosite/geosite.proto

package geosite

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Domain_Type int32

const (
	Domain_Plain  Domain_Type = 0
	Domain_Regex  Domain_Type = 1
	Domain_Domain Domain_Type = 2
	Domain_Full   Domain_Type = 3
)

// Enum value maps for Domain_Type.
var (
	Domain_Type_name = map[int32]string{
		0: "Plain",
		1: "Regex",
		2: "Domain",
		3: "Full",
	}
	Domain_Type_value = map[string]int32{
		"Plain":  0,
		"Regex":  1,
		"Domain": 2,
		"Full":   3,
	}
)

func (x Domain_Type) Enum() *Domain_Type {
	p := new(Domain_Type)
	*p = x
	return p
}

func (x Domain_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Domain_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_geosite_geosite_proto_enumTypes[0].Descriptor()
}

func (Domain_Type) Type() protoreflect.EnumType {
	return &file_internal_geosite_geosite_proto_enumTypes[0]
}

func (x Domain_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Domain_Type.Descriptor instead.
func (Domain_Type) EnumDescriptor() ([]byte, []int) {
	return file_internal_geosite_geosite_proto_rawDescGZIP(), []int{1, 0}
}

// DomainAttribute carries the attribute key attached to a domain entry.
// The original v2ray proto also has a oneof value (bool/int); we only need
// the key for attr-based filtering, so extra fields are silently ignored by
// proto.Unmarshal.
type DomainAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainAttribute) Reset() {
	*x = DomainAttribute{}
	mi := &file_internal_geosite_geosite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainAttribute) ProtoMessage() {}

func (x *DomainAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_internal_geosite_geosite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainAttribute.ProtoReflect.Descriptor instead.
func (*DomainAttribute) Descriptor() ([]byte, []int) {
	return file_internal_geosite_geosite_proto_rawDescGZIP(), []int{0}
}

func (x *DomainAttribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Domain mirrors the v2ray Domain message. Type enum values match the
// upstream definition: 0=Plain(keyword), 1=Regex, 2=Domain(suffix), 3=Full.
type Domain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Domain_Type            `protobuf:"varint,1,opt,name=type,proto3,enum=geosite.Domain_Type" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Attribute     []*DomainAttribute     `protobuf:"bytes,3,rep,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_internal_geosite_geosite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_internal_geosite_geosite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_internal_geosite_geosite_proto_rawDescGZIP(), []int{1}
}

func (x *Domain) GetType() Domain_Type {
	if x != nil {
		return x.Type
	}
	return Domain_Plain
}

func (x *Domain) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Domain) GetAttribute() []*DomainAttribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

// GeoSite is one list keyed by country/category code.
type GeoSite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Domains       []*Domain              `protobuf:"bytes,2,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoSite) Reset() {
	*x = GeoSite{}
	mi := &file_internal_geosite_geosite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoSite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoSite) ProtoMessage() {}

func (x *GeoSite) ProtoReflect() protoreflect.Message {
	mi := &file_internal_geosite_geosite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoSite.ProtoReflect.Descriptor instead.
func (*GeoSite) Descriptor() ([]byte, []int) {
	return file_internal_geosite_geosite_proto_rawDescGZIP(), []int{2}
}

func (x *GeoSite) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *GeoSite) GetDomains() []*Domain {
	if x != nil {
		return x.Domains
	}
	return nil
}

// GeoSiteList is the top-level container of the geosite.dat file.
type GeoSiteList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         []*GeoSite             `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoSiteList) Reset() {
	*x = GeoSiteList{}
	mi := &file_internal_geosite_geosite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoSiteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoSiteList) ProtoMessage() {}

func (x *GeoSiteList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_geosite_geosite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoSiteList.ProtoReflect.Descriptor instead.
func (*GeoSiteList) Descriptor() ([]byte, []int) {
	return file_internal_geosite_geosite_proto_rawDescGZIP(), []int{3}
}

func (x *GeoSiteList) GetEntry() []*GeoSite {
	if x != nil {
		return x.Entry
	}
	return nil
}

var File_internal_geosite_geosite_proto protoreflect.FileDescriptor

const file_internal_geosite_geosite_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/geosite/geosite.proto\x12\ageosite\"#\n" +
	"\x0fDomainAttribute\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\xb4\x01\n" +
	"\x06Domain\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.geosite.Domain.TypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x126\n" +
	"\tattribute\x18\x03 \x03(\v2\x18.geosite.DomainAttributeR\tattribute\"2\n" +
	"\x04Type\x12\t\n" +
	"\x05Plain\x10\x00\x12\t\n" +
	"\x05Regex\x10\x01\x12\n" +
	"\n" +
	"\x06Domain\x10\x02\x12\b\n" +
	"\x04Full\x10\x03\"W\n" +
	"\aGeoSite\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x12)\n" +
	"\adomains\x18\x02 \x03(\v2\x0f.geosite.DomainR\adomains\"5\n" +
	"\vGeoSiteList\x12&\n" +
	"\x05entry\x18\x01 \x03(\v2\x10.geosite.GeoSiteR\x05entryB@Z>github.com/fl0w1nd/proxy-rule-manager/internal/geosite;geositeb\x06proto3"

var (
	file_internal_geosite_geosite_proto_rawDescOnce sync.Once
	file_internal_geosite_geosite_proto_rawDescData []byte
)

func file_internal_geosite_geosite_proto_rawDescGZIP() []byte {
	file_internal_geosite_geosite_proto_rawDescOnce.Do(func() {
		file_internal_geosite_geosite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_geosite_geosite_proto_rawDesc), len(file_internal_geosite_geosite_proto_rawDesc)))
	})
	return file_internal_geosite_geosite_proto_rawDescData
}

var file_internal_geosite_geosite_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_geosite_geosite_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_geosite_geosite_proto_goTypes = []any{
	(Domain_Type)(0),        // 0: geosite.Domain.Type
	(*DomainAttribute)(nil), // 1: geosite.DomainAttribute
	(*Domain)(nil),          // 2: geosite.Domain
	(*GeoSite)(nil),         // 3: geosite.GeoSite
	(*GeoSiteList)(nil),     // 4: geosite.GeoSiteList
}
var file_internal_geosite_geosite_proto_depIdxs = []int32{
	0, // 0: geosite.Domain.type:type_name -> geosite.Domain.Type
	1, // 1: geosite.Domain.attribute:type_name -> geosite.DomainAttribute
	2, // 2: geosite.GeoSite.domains:type_name -> geosite.Domain
	3, // 3: geosite.GeoSiteList.entry:type_name -> geosite.GeoSite
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_geosite_geosite_proto_init() }
func file_internal_geosite_geosite_proto_init() {
	if File_internal_geosite_geosite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_geosite_geosite_proto_rawDesc), len(file_internal_geosite_geosite_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_geosite_geosite_proto_goTypes,
		DependencyIndexes: file_internal_geosite_geosite_proto_depIdxs,
		EnumInfos:         file_internal_geosite_geosite_proto_enumTypes,
		MessageInfos:      file_internal_geosite_geosite_proto_msgTypes,
	}.Build()
	File_internal_geosite_geosite_proto = out.File
	file_internal_geosite_geosite_proto_goTypes = nil
	file_internal_geosite_geosite_proto_depIdxs = nil
}
